services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "bookhub"
    ports:
      - "5432:5432"
    volumes:
      - ./docker/postgres/initdb.sql:/docker-entrypoint-initdb.d/initdb.sql
