spring:
  application:
    name: "bookhub"
  flyway:
    enabled: true
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/bookhub}
    username: ${SPRING_DATASOURCE_USER:admin}
    password: ${SPRING_DATASOURCE_PASSWORD:admin}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        generate_statistics: false
jwt:
  public:
    key: ${JWT_PUBLIC_KEY:classpath:keys/public.pem}
  private:
    key: ${JWT_PRIVATE_KEY:classpath:keys/private.pem}
server:
  port: 8080
  servlet:
    context-path: /bookhub
  error:
    include-message: always
